<?php

class lib4riMetaDataIntegrator {
    
    private $authors = array(); //DOM element?
    
    /**
     * Constructor
     */
    public function __construct() {
        
    }
    
    protected function matchAuthor(){
        
    }
    
    protected function getInternalAffiliation(){
        
    }
    
}

class eawagMetaDataIntegrator extends lib4riMetaDataIntegrator{
    
}

class empaMetaDataIntegrator extends lib4riMetaDataIntegrator{
    
}

class wslMetaDataIntegrator extends lib4riMetaDataIntegrator{
    
}

class psiMetaDataIntegrator extends lib4riMetaDataIntegrator{
    
}